[build]
  functions = "netlify/functions"
  publish = "."

[[headers]]
  for = "/"
  [headers.values]
    X-Puzzle-Key = "1amth3key-y0u-luckyb4st4rd"

[[headers]]
  for = "/index.html"
  [headers.values]
    X-Puzzle-Key = "1amth3key-y0u-luckyb4st4rd"
